
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/cyberdelia/go-metrics-graphite"

[[constraint]]
  name = "github.com/evalphobia/logrus_sentry"
  version = "0.4.1"

[[constraint]]
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "0.9.0"

[[constraint]]
  name = "github.com/ogier/pflag"
  version = "0.0.1"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

# Remove once https://github.com/golang/go/issues/22688 is fixed
[[override]]
  name = "golang.org/x/sys"
  revision = "665f6529cca930e27b831a0d1dafffbe1c172924"